gifa/dashboard/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.gifa_dashboard, name='gifa_dashboard'),
    url(r'^affected_family/$', views.panel_affected_family, name = 'panel_affected_family'),
    url(r'^humanitarian_aid/$', views.panel_humanitarian_aid, name = 'panel_humanitarian_aid'),
    url(r'^dataviz/$', views.panel_visualization, name = 'panel_visualization'),
    url(r'^vulnerability/$', views.panel_vulnerability, name = 'panel_vulnerability'),
    url(r'^exposure/$', views.panel_exposure, name = 'panel_exposure'),
    url(r'^bangunanosm/$', views.panel_bangunanosm, name = 'panel_bangunanosm'),
]

gifa/gifa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from .views import page_home


adminurlpattern = [url(r'^admin/', admin.site.urls)]

urlpatterns = adminurlpattern + [
    url(r'^$', page_home, name='home'),
    url(r'^dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    url(r'^odkcollect/', include(('odkcollect.urls', 'odkcollect'), namespace='odkcollect')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

admin.site.site_header = settings.SITE_NAME
admin.site.site_title = settings.SITE_NAME

gifa/dashboard/models.py
from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from odkcollect.models import ODKConnector
import django_tables2 as tables


class BangunanOSM(models.Model):
    id = models.BigIntegerField(
        primary_key=True,
        verbose_name=_('ID')
    )
    nama = models.CharField(
        max_length=255,
        verbose_name=_('Nama')
    )
    jenis_bangunan = models.CharField(
        max_length=255,
        verbose_name=_('Connection Name')
    )
    polygon = models.MultiPolygonField(
        null=True,
        blank=True,
        verbose_name=_('Polygon')
    )
    exposure_index = models.IntegerField(
        null=True,
        blank=True,
        default=0,
        verbose_name=_('Exposure Index')
    )
    flood_depth = models.IntegerField(
        null=True,
        blank=True,
        default=0,
        verbose_name=_('Flood Depth')
    )


class InfrastrukturJalanOSM(models.Model):
    id = models.BigIntegerField(
        primary_key=True,
        verbose_name=_('ID')
    )
    nama = models.CharField(
        max_length=255,
        verbose_name=_('Nama')
    )
    jenis_jalan = models.CharField(
        max_length=255,
        verbose_name=_('Jenis Jalan')
    )
    keterangan = models.CharField(
        max_length=255,
        verbose_name=_('Keterangan')
    )
    polyline = models.MultiLineStringField(
        null=True,
        blank=True,
        verbose_name=_('Polyline')
    )


class SesarLembang(models.Model):
    id = models.BigIntegerField(
        primary_key=True,
        verbose_name=_('ID')
    )
    polyline = models.MultiLineStringField(
        null=True,
        blank=True,
        verbose_name=_('Polyline')
    )


class IntensitasGempa(models.Model):
    id = models.BigIntegerField(
        primary_key=True,
        verbose_name=_('ID')
    )
    polygon = models.MultiPolygonField(
        null=True,
        blank=True,
        verbose_name=_('Polygon')
    )
    luas = models.DecimalField(
        null=True,
        blank=True,
        max_digits=25,
        decimal_places=4,
        help_text=_('dalam meter persegi'),
        verbose_name=_('Luas')
    )
    value = models.DecimalField(
        null=True,
        blank=True,
        max_digits=25,
        decimal_places=4,
        help_text=_('dalam SR'),
        verbose_name=_('value')
    )


class RendamanBanjir(models.Model):
    id = models.BigIntegerField(
        primary_key=True,
        verbose_name=_('ID')
    )
    polygon = models.MultiPolygonField(
        null=True,
        blank=True,
        verbose_name=_('Polygon')
    )
    luas = models.DecimalField(
        null=True,
        blank=True,
        max_digits=25,
        decimal_places=4,
        help_text=_('dalam meter persegi'),
        verbose_name=_('Luas')
    )


class Desa(models.Model):
    id = models.BigIntegerField(
        primary_key=True,
        verbose_name=_('ID')
    )
    nama = models.CharField(
        max_length=255,
        verbose_name=_('Nama')
    )
    polygon = models.MultiPolygonField(
        null=True,
        blank=True,
        verbose_name=_('Polygon')
    )
    luas = models.DecimalField(
        null=True,
        blank=True,
        max_digits=25,
        decimal_places=4,
        help_text=_('dalam kilometer persegi'),
        verbose_name=_('Luas')
    )
    catatan = models.TextField(
        blank=True,
        verbose_name=_('Catatan')
    )


    class Meta:
        ordering = ['pk']
        get_latest_by = 'pk'
        verbose_name_plural = _('Desa')

    def __unicode__(self):
        return self.nama


class Category(models.Model):
    category_name = models.CharField(
        max_length=255,
        verbose_name=_('Category Name')
    )
    odk_connections = models.ManyToManyField(
        ODKConnector,
        verbose_name=_('ODK Conncetions List ID'),
    )


    class Meta:
        ordering = ['pk']
        get_latest_by = 'pk'
        verbose_name_plural = _('Category')

    def __unicode__(self):
        return self.category_name

gifa/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os, json, urllib, json

from django.shortcuts import render
from django.utils.safestring import mark_safe
from django.core.serializers import serialize
from django.http import JsonResponse, HttpResponse
from django.db.models import Q
from django.db import connection

from dashboard.models import Desa, Category, BangunanOSM
from odkcollect.models import ODKConnector
from mapservice.models import MapServices, LayerServices

def gifa_dashboard(request):
    """
    GIFA Dashboard
    """
    # Desa Boundary
    desa_bndy = Desa.objects.filter(Q(nama='BALEENDAH') | Q(nama='ANDIR'))
    desa_bndy_json = serialize(
        'geojson',
        desa_bndy,
        geometry_field='polygon',
        fields=('nama', 'luas', 'catatan')
    )

    # ODK Polyline
    all_odk_polyline = ODKConnector.objects.filter(
        publish=True,
        geometry_type='polyline'
    )

    # ODK Polygon
    all_odk_polygon = ODKConnector.objects.filter(
        publish=True,
        geometry_type='polygon'
    )

    # ODK Point
    all_odk_point = ODKConnector.objects.filter(
        publish=True,
        geometry_type='point'
    )

    # Marker icon resource from Map Box
    marker_url = "https://api.tiles.mapbox.com/v3/marker/pin-s-circle-stroked"

    # WMS Services
    all_map_services = MapServices.objects.filter(
        publish=True
    )

    # BIG Basemap Services
    urlPetaBIG = "https://portal.ina-sdi.or.id/arcgis/rest/services/IGD/RupabumiIndonesia/MapServer"
    urlBaruPetaBIG = "http://palapa.big.go.id:8080/geoserver/gwc/service/tms/1.0.0/basemap_rbi:basemap@EPSG:3857@png/{z}/{x}/{-y}.png"

    # category
    all_category = Category.objects.all()

    context = {
        "desa_bndy_json": desa_bndy_json,
        "all_odk_polyline": all_odk_polyline,
        "all_odk_polygon": all_odk_polygon,
        "all_odk_point": all_odk_point,
        "all_category": all_category,
        "marker_url": marker_url,
        "urlPetaBIG": urlPetaBIG,
        "urlBaruPetaBIG": urlBaruPetaBIG,
        "all_map_services": all_map_services
    }

    return render(request, 'dashboard/index.html', context)

def panel_affected_family(request):
    return render(request, 'dashboard/affected_family.html')

def panel_humanitarian_aid(request):
    return render(request, 'dashboard/humanitarian_aid.html')

def panel_visualization(request):
    return render(request, 'dashboard/dataviz.html')

def panel_vulnerability(request):
    return render(request, 'dashboard/vulnerability.html')

def panel_exposure(request):
    return render(request, 'dashboard/exposure.html')

def panel_bangunanosm(request):
    # Getting data from database
    bangunan_osm = BangunanOSM.objects.values('id', 'nama', 'jenis_bangunan', 'exposure_index', 'flood_depth')
    bangunan_osm_json = json.dumps({"data": list(bangunan_osm)})
    data = {'bangunan_osm': bangunan_osm_json, }
    return HttpResponse(bangunan_osm_json, content_type="application/json")

gifa/dashboard/templates/dashboard/includes/block_about_modal.html
{% load staticfiles %}

<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Welcome to the GIFA!</h4>
      </div>
      <div class="modal-body">
        <ul class="nav nav-tabs nav-justified" id="aboutTabs">
          <li class="active"><a href="#about" data-toggle="tab"><i class="fa fa-question-circle"></i>&nbsp;About the project</a></li>
          <li><a href="#contact" data-toggle="tab"><i class="fa fa-envelope"></i>&nbsp;Contact us</a></li>
          <li><a href="#disclaimer" data-toggle="tab"><i class="fa fa-exclamation-circle"></i>&nbsp;Disclaimer</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-globe"></i>&nbsp;Metadata <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#boroughs-tab" data-toggle="tab">Boroughs</a></li>
              <li><a href="#subway-lines-tab" data-toggle="tab">Subway Lines</a></li>
              <li><a href="#theaters-tab" data-toggle="tab">Theaters</a></li>
              <li><a href="#museums-tab" data-toggle="tab">Museums</a></li>
            </ul>
          </li>
        </ul>
        <div class="tab-content" id="aboutTabsContent">
          <div class="tab-pane fade active in" id="about">
            <p>A simple, responsive template for building web mapping applications with <a href="http://getbootstrap.com/">Bootstrap 3</a>, <a href="http://leafletjs.com/" target="_blank">Leaflet</a>, and <a href="http://twitter.github.io/typeahead.js/" target="_blank">typeahead.js</a>. Open source, MIT licensed, and available on <a href="https://github.com/bmcbride/bootleaf" target="_blank">GitHub</a>.</p>
            <div class="panel panel-primary">
              <div class="panel-heading">Features</div>
              <ul class="list-group">
                <li class="list-group-item">Fullscreen mobile-friendly map template with responsive navbar and modal placeholders</li>
                <li class="list-group-item">jQuery loading of external GeoJSON files</li>
                <li class="list-group-item">Logical multiple layer marker clustering via the <a href="https://github.com/Leaflet/Leaflet.markercluster" target="_blank">leaflet marker cluster plugin</a></li>
                <li class="list-group-item">Elegant client-side multi-layer feature search with autocomplete using <a href="http://twitter.github.io/typeahead.js/" target="_blank">typeahead.js</a></li>
                <li class="list-group-item">Responsive sidebar feature list synced with map bounds, which includes sorting and filtering via <a href="http://listjs.com/" target="_blank">list.js</a></li>
                <li class="list-group-item">Marker icons included in grouped layer control via the <a href="https://github.com/ismyrnow/Leaflet.groupedlayercontrol" target="_blank">grouped layer control plugin</a></li>
              </ul>
            </div>
          </div>
          <div id="disclaimer" class="tab-pane fade text-danger">
            <p>The data provided on this site is for informational and planning purposes only.</p>
            <p>Absolutely no accuracy or completeness guarantee is implied or intended. All information on this map is subject to such variations and corrections as might result from a complete title search and/or accurate field survey.</p>
          </div>
          <div class="tab-pane fade" id="contact">
            <form id="contact-form">
              <div class="well well-sm">
                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="first-name">First Name:</label>
                      <input type="text" class="form-control" id="first-name">
                    </div>
                    <div class="form-group">
                      <label for="last-name">Last Name:</label>
                      <input type="text" class="form-control" id="last-email">
                    </div>
                    <div class="form-group">
                      <label for="email">Email:</label>
                      <input type="text" class="form-control" id="email">
                    </div>
                  </div>
                  <div class="col-md-8">
                    <label for="message">Message:</label>
                    <textarea class="form-control" rows="8" id="message"></textarea>
                  </div>
                  <div class="col-md-12">
                    <p>
                      <button type="submit" class="btn btn-primary pull-right" data-dismiss="modal">Submit</button>
                    </p>
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="tab-pane fade" id="boroughs-tab">
            <p>Borough data courtesy of <a href="http://www.nyc.gov/html/dcp/pdf/bytes/nybbwi_metadata.pdf" target="_blank">New York City Department of City Planning</a></p>
          </div>
          <div class="tab-pane fade" id="subway-lines-tab">
            <p><a href="http://spatialityblog.com/2010/07/08/mta-gis-data-update/#datalinks" target="_blank">MTA Subway data</a> courtesy of the <a href="http://www.urbanresearch.org/about/cur-components/cuny-mapping-service" target="_blank">CUNY Mapping Service at the Center for Urban Research</a></p>
          </div>
          <div class="tab-pane fade" id="theaters-tab">
            <p>Theater data courtesy of <a href="https://data.cityofnewyork.us/Recreation/Theaters/kdu2-865w" target="_blank">NYC Department of Information & Telecommunications (DoITT)</a></p>
          </div>
          <div class="tab-pane fade" id="museums-tab">
            <p>Museum data courtesy of <a href="https://data.cityofnewyork.us/Recreation/Museums-and-Galleries/sat5-adpb" target="_blank">NYC Department of Information & Telecommunications (DoITT)</a></p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

gifa/dashboard/templates/dashboard/includes/block_attribution_modal.html
{% load staticfiles %}

<div class="modal fade" id="attributionModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">
          Developed by <a href='#'>CI-SITU / GIFA Team</a>
        </h4>
      </div>
      <div class="modal-body">
        <div id="attribution"></div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

gifa/dashboard/templates/dashboard/includes/block_feature_modal.html
{% load staticfiles %}

{% block extra_css %}
<style>
    @media (min-width: 768px) {
      .modal-xl {
        width: 90%;
        max-width:1200px;
      }
    }
    #featureModal .modal-content {
        background-color: #fff;
    }
    #featureModal .table-striped>tbody>tr:nth-of-type(odd) {
        background-color: #47798f9e;
    }
    #featureModal .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th,
    #featureModal .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th,
    #featureModal .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
        border: 2px solid #28375b;
        color: #091636;
    }
    #featureModal .text-primary {
        color: #28375b;
    }
</style>
{% endblock %}

<div class="modal fade" id="featureModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title text-primary" id="feature-title"></h4>
      </div>
      <div class="modal-body" id="feature-info">
          <div id="geointel-info"></div>
          <hr>
          <div id="attribute-info"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

gifa/dashboard/templates/dashboard/includes/block_legend_modal.html
{% load staticfiles %}

<div class="modal fade" id="legendModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Map Legend</h4>
      </div>
      <div class="modal-body">
        <p>Map Legend goes here...</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

gifa/dashboard/templates/dashboard/includes/block_loadbar.html
{% load staticfiles %}

<div id="loading">
  <div class="loading-indicator">
    <div class="progress progress-striped active">
      <div class="progress-bar progress-bar-info progress-bar-full"></div>
    </div>
  </div>
</div>

gifa/dashboard/templates/dashboard/includes/block_login_modal.html
{% load staticfiles %}

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Login</h4>
      </div>
      <div class="modal-body">
        <form id="contact-form">
          <fieldset>
            <div class="form-group">
              <label for="name">Username:</label>
              <input type="text" class="form-control" id="username">
            </div>
            <div class="form-group">
              <label for="email">Password:</label>
              <input type="password" class="form-control" id="password">
            </div>
          </fieldset>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary" data-dismiss="modal">Login</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

gifa/dashboard/templates/dashboard/includes/block_map_modal.html
{% load staticfiles %}

<!-- Modal -->
<div class="modal fade" id="modalMap" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    
  </div>
</div>

gifa/dashboard/templates/dashboard/includes/block_navbar.html
{% load staticfiles %}

{% block extra_css %}
<style>
    #gifaNavbar {
        padding: 8px;
        background-color: #fff;
        border-color: #c6c6c6;
    }
    #gifaIcon {
        width: 32px;
        margin: 2px;
        margin-left:10px;
    }
    #navbarMenu {
        margin-left: 5%;
    }
    #navbarMenu>.open>a,
    #navbarMenu>.open>a:focus,
    #navbarMenu>.open>a:hover {
        color: #1d4cbc;
        background-color: #f8f8f8;
    }
    #navbarMenu>li>a,
    #navbarMenu>li>a>i{
        color: #506eb5;
        font-size: 1.05em;
    }
    #navbarMenu>li>ul>li>a,
    #navbarMenu>li>ul>li>a>i{
        color: #506eb5;
    }
</style>
{% endblock %}

<div id="gifaNavbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-icon-container">
        <a href="#" class="navbar-icon pull-right visible-xs" id="nav-btn"><i class="fa fa-bars fa-lg"></i></a>
        <a href="#" class="navbar-icon pull-right visible-xs" id="sidebar-toggle-btn"><i class="fa fa-search fa-lg"></i></a>
      </div>
        <a href="{% url 'home' %}" %}">
          <img id="gifaIcon" src="{% static 'icon/gifa.png' %}">
        </a>
    </div>
    {% if request.path != '/' %}
    <div class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group has-feedback">
            <input id="searchbox" type="text" placeholder="Search" class="form-control">
            <span id="searchicon" class="fa fa-search form-control-feedback"></span>
        </div>
      </form>
      <ul id="navbarMenu" class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a id="toolDrop" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-globe" style="font-size:20px;"></i>&nbsp;&nbsp;Tools<b class="caret"></b></a>
            <ul class="dropdown-menu">
              {% if request.path == '/dashboard/' %}
              <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="full-extent-btn"><i class="fa fa-arrows-alt"></i>&nbsp;&nbsp;Zoom To Full Extent</a></li>
              <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="legend-btn"><i class="fa fa-picture-o"></i>&nbsp;&nbsp;Show Legend</a></li>
              {% else %}
              <li><a href="{% url 'dashboard:gifa_dashboard' %}" ><i class="fa fa-dashboard"></i>&nbsp;&nbsp;Dashboard</a></li>
              {% endif %}
              <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="pjt2awlr-btn"><img src="http://pjt2awlr.com/favicon.ico">&nbsp;&nbsp;PJT2AWLR Data</a></li>
              <li class="divider hidden-xs"></li>
              <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="login-btn"><i class="fa fa-user"></i>&nbsp;&nbsp;Login</a></li>
            </ul>
          </li>
      </ul>
      <ul id="navbarMenu" class="nav navbar-nav">
        {% if request.path == '/dashboard/' %}
        <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="about-btn"><i class="fa fa-question-circle white"></i>&nbsp;&nbsp;About</a></li>
        <li class="hidden-xs"><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="list-btn"><i class="fa fa-list white"></i>&nbsp;&nbsp;POI List</a></li>
        <li class="dropdown">
            <a class="dropdown-toggle" id="downloadDrop" href="#" role="button" data-toggle="dropdown"><i class="fa fa-database white"></i>&nbsp;&nbsp;Data <b class="caret"></b></a>
            <ul class="dropdown-menu">
              {% for odk_polyline in all_odk_polyline %}
              <li><a href="{% static 'data/boroughs.geojson' %}" download="{{ odk_polyline.con_nama }}.zip" target="_blank" data-toggle="collapse" data-target=".navbar-collapse.in"><div style='border-bottom: 4px solid {{ odk_polyline.object_color }};margin-bottom:0.3em;width:1.5em;display:inline-block;'></div>&nbsp;&nbsp;{{ odk_polyline.con_nama }}</a></li>
              {% endfor %}
              {% for odk_point in all_odk_point %}
              <li><a href="{% static 'data/boroughs.geojson' %}" download="{{ odk_point.con_nama }}.zip" target="_blank" data-toggle="collapse" data-target=".navbar-collapse.in"><img src='{{ marker_url }}+{{ odk_point.object_color|slice:"1:" }}.png'>&nbsp;&nbsp;{{ odk_point.con_nama }}</a></li>
              {% endfor %}
              {% for odk_polygon in all_odk_polygon %}
              <li><a href="{% static 'data/boroughs.geojson' %}" download="{{ odk_polygon.con_nama }}.zip" target="_blank" data-toggle="collapse" data-target=".navbar-collapse.in"><div style='background-color: {{ odk_polygon.object_color }};padding:0px;width:1.4em;height:1.4em;display:inline-block;'></div>&nbsp;{{ con.con_nama }}&nbsp;&nbsp;&nbsp;&nbsp;{{ odk_point.con_nama }}</a></li>
              {% endfor %}
              <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="shapefile-btn"><i class="fa fa-download"></i>&nbsp;&nbsp;Shapefile</a></li>
              <li class="divider hidden-xs"></li>
              <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" id="service-btn"><i class="fa fa-cloud-download"></i>&nbsp;&nbsp;Services</a></li>
            </ul>
        </li>
        {% endif %}
        <li class="dropdown">
            <a class="dropdown-toggle" id="disasterDrop" href="#" role="button" data-toggle="dropdown"><i class="fa fa-hospital-o"></i>&nbsp;&nbsp;Disaster Assessment <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/dashboard/affected_family"><i class="fa fa-hospital-o"></i>&nbsp;&nbsp;Affected Family</a></li>
              <li><a href="/dashboard/humanitarian_aid"><i class="fa fa-hospital-o"></i>&nbsp;&nbsp;Humanitarian Needs Assessment</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" id="statisticDrop" href="#" role="button" data-toggle="dropdown"><i class="fa fa-bar-chart"></i>&nbsp;&nbsp;Statistics & Visualization <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li class="dropdown-submenu">
                    <a tabindex="-1" href="#">History Data</a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Flood</a></li>
                        <li><a href="#">Earthquake</a></li>
                    </ul>
                </li>
                <li><a href="#"><i class="fa fa-hospital-o"></i>&nbsp;&nbsp;BPS</a></li>
                <li><a href="/dashboard/dataviz"><i class="fa fa-bar-chart"></i>&nbsp;&nbsp;Humanitarian Needs Assessment</a></li>
                <li class="menu-item dropdown dropdown-submenu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Disaster Risk</a>
                    <ul class="dropdown-menu">
                        <li class="menu-item ">
                            <a href="/dashboard/vulnerability">Vulnerability Index</a>
                        </li>
                        <li class="menu-item ">
                            <a href="/dashboard/exposure">Exposure Index</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
      </ul>
      {% else %}
        <ul id="navbarMenu" class="nav navbar-nav">
          <li><a href="{% url 'dashboard:gifa_dashboard' %}">Dashboard</a></li>
        </ul>
      {% endif %}
    </div><!--/.navbar-collapse -->
  </div>
</div>